function usePlateList() {
  return [
    {
      id: 1,
      cover: "/img/beatles.jpg",
      albumName: "Abbey Road",
      name: "The Beatles",
      year: "1969",
      genre: "Rock",
      style: [18, 4, 3],
      country: "United Kingdom",
    },
    {
      id: 2,
      cover: "/img/roling-stones.jpg",
      albumName: "Only Rock & Roll?",
      name: "The Rolling Stones",
      year: "1980",
      genre: "Rock",
      style: [2, 9, 8, 4, 7],
      country: "England",
    },
    {
      id: 3,
      cover: "/img/elvis.jpg",
      albumName: "Welcome To My World",
      name: "Elvis Presley",
      year: "1977",
      genre: "Rock",
      style: [6, 17],
      country: "USA",
    },
    {
      id: 4,
      cover: "/img/pink-floyd.jpg",
      albumName: "The Dark Side Of The Moon",
      name: "Pink Floyd",
      year: "1973",
      genre: "Rock",
      style: [16, 15],
      country: "United Kingdom",
    },
    {
      id: 5,
      cover: "/img/iron-maiden.jpg",
      albumName: "A Real Live One",
      name: "Iron Maiden",
      year: "1993",
      genre: "Metal",
      style: [1],
      country: "United Kingdom",
    },
    {
      id: 6,
      cover: "/img/metallica.jpg",
      albumName: "Load",
      name: "Metallica",
      year: "1996",
      genre: "Rock",
      style: [14, 12],
      country: "USA",
    },
    {
      id: 7,
      cover: "/img/led-zepelin.jpg",
      albumName: "Celebration Day",
      name: "Led Zeppelin",
      year: "2012",
      genre: "Alternative",
      style: [12, 10],
      country: "United Kingdom",
    },
    {
      id: 8,
      cover: "/img/alice-cooper.jpg",
      albumName: "Billion Dollar Babies",
      name: "Alice Cooper",
      year: "1973",
      genre: "Rock",
      style: [12, 11, 10],
      country: "USA",
    },
    {
      id: 9,
      cover: "/img/manowar.jpg",
      albumName: "Kings Of Metal",
      name: "Manowar",
      year: "1988",
      genre: "Metal",
      style: [13, 1],
      country: "USA",
    },
    {
      id: 10,
      cover: "/img/hammerfall.jpg",
      albumName: "Legacy Of Kings",
      name: "Hammerfall",
      year: "1998",
      genre: "Metal",
      style: [1],
      country: "Sweden",
    },
  ];
}

export default usePlateList;
